### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by krosenfeld-IDM** [sciris/datathief#1]
After installing datathief via `pip install datathief`, I tried running the example and received an error:

```
Traceback (most recent call last):
  File "C:/Users/krosenfeld/Documents/projects/covid_econ_vaccines/pfizer_incidence/process_figure_data.py", line 4, in <module>
    import datathief as dt
  File "C:\Users\krosenfeld\Documents\projects\covid_vaccines\envs\lib\site-packages\datathief\__init__.py", line 1, in <module>
    from .datathief import *
  File "<fstring>", line 1
    (img.shape=)
              ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

I think errors out on the line in `datathief.py`:

https://github.com/sciris/datathief/blob/6c9dc0c42b8dc4a9fbe35bad007d0c64dcb2c046/datathief/datathief.py#L88

I'm using python 3.7.9

**Comment by cliffckerr** [comment]
@krosenfeld-IDM Yes, this is new in Python 3.8:
https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging
Probably was a little ambitious to convert already :) It should work if `debug=False`

**Comment by krosenfeld-IDM** [comment]
@cliffckerr - it seems to be erroring out for me even with the default `debug=False`.  That's a nice new feature though!

**Comment by cliffckerr** [comment]
@krosenfeld-IDM Ah yeah good point, I guess because it's a syntax error in <=3.7 it won't even parse the file. OK, I'll switch to friendlier notation :)
